import ij.IJ;
import ij.ImagePlus;
import ij.gui.TextRoi;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * FinalizePC.java
 *
 * Created on Jul 2, 2012, 4:21:57 PM
 */
/**
 * Copyright Jun 7, 2012 The GAIA Group http://gaiag.net
 *
 * @author chris
 */
public class FinalizePC extends javax.swing.JFrame {

    /**
     * Creates new form FinalizePC
     */
    public FinalizePC() {
        initComponents();

        smallerFontButton.setOpaque(true);
        smallerFontButton.setBackground(Color.CYAN);

        largerFontButton.setOpaque(true);
        largerFontButton.setBackground(Color.CYAN);

        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);

        String s1 = "To write something on the front of the postcard,"
                + "\nclick on the image and start typing. Use the"
                + "\nbuttons to change the font style, size and color."
                + "\nClick and drag to where you want the message."
                + "\nClick the Finish button to complete your card.";
        toTextWindow(s1, false);

        imp = IJ.getImage(); // AAPC_Var.getImage();

//        imp = IJ.openImage("/Users/chris/Documents/GAIA_Projects/*Daniel Weth /testImages/Argonauti.tif");
        imp.show();

        moveWindow(imp, 400, 0);

        IJ.setTool("text");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        finalizePanel = new javax.swing.JPanel();
        smallerFontButton = new javax.swing.JButton();
        largerFontButton = new javax.swing.JButton();
        fontColorLabel = new javax.swing.JLabel();
        fontBlackLabel = new javax.swing.JLabel();
        fontRedLabel = new javax.swing.JLabel();
        fontGreenLabel = new javax.swing.JLabel();
        fontPurpleLabel = new javax.swing.JLabel();
        fontTypeLabel = new javax.swing.JLabel();
        font1Label = new javax.swing.JLabel();
        font3Label = new javax.swing.JLabel();
        font4Label = new javax.swing.JLabel();
        font5Label = new javax.swing.JLabel();
        finalizeButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        instructionScrollPane = new javax.swing.JScrollPane();
        instructionTextArea = new javax.swing.JTextArea();
        colorBlackLabel = new javax.swing.JLabel();
        colorWhiteLabel = new javax.swing.JLabel();
        color3Label = new javax.swing.JLabel();
        color4Label = new javax.swing.JLabel();
        color5Label = new javax.swing.JLabel();
        color6Label = new javax.swing.JLabel();
        color7Label = new javax.swing.JLabel();
        color8Label = new javax.swing.JLabel();
        color9Label = new javax.swing.JLabel();
        color10Label = new javax.swing.JLabel();
        color11Label = new javax.swing.JLabel();
        color12Label = new javax.swing.JLabel();
        color13Label = new javax.swing.JLabel();
        color14Label = new javax.swing.JLabel();
        color15Label = new javax.swing.JLabel();
        font6Label = new javax.swing.JLabel();
        font2Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 73, 125));

        finalizePanel.setBackground(new java.awt.Color(31, 73, 125));

        smallerFontButton.setBackground(new java.awt.Color(50, 255, 255));
        smallerFontButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        smallerFontButton.setText("Smaller Font");
        smallerFontButton.setMargin(new java.awt.Insets(0, 5, 0, 5));
        smallerFontButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                smallerFontMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                smallFontMouseReleased(evt);
            }
        });
        smallerFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallerFontButtonActionPerformed(evt);
            }
        });

        largerFontButton.setBackground(new java.awt.Color(102, 204, 255));
        largerFontButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        largerFontButton.setText("Larger Font");
        largerFontButton.setMargin(new java.awt.Insets(0, 5, 0, 5));
        largerFontButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                largerFontMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                largeFontMouseReleased(evt);
            }
        });
        largerFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largerFontButtonActionPerformed(evt);
            }
        });

        fontColorLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        fontColorLabel.setForeground(new java.awt.Color(230, 224, 236));
        fontColorLabel.setText("Please choose the font color");

        fontBlackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackClicked(evt);
            }
        });

        fontRedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redClicked(evt);
            }
        });

        fontGreenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenClicked(evt);
            }
        });

        fontPurpleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleClicked(evt);
            }
        });

        fontTypeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        fontTypeLabel.setForeground(new java.awt.Color(230, 224, 236));
        fontTypeLabel.setText("Please choose the font type");

        font1Label.setBackground(new java.awt.Color(51, 153, 255));
        font1Label.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        font1Label.setForeground(new java.awt.Color(230, 224, 236));
        font1Label.setText("Greetings");
        font1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font1Clicked(evt);
            }
        });

        font3Label.setBackground(new java.awt.Color(51, 153, 255));
        font3Label.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        font3Label.setForeground(new java.awt.Color(230, 224, 236));
        font3Label.setText("Greetings");
        font3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font3Clicked(evt);
            }
        });

        font4Label.setBackground(new java.awt.Color(51, 153, 255));
        font4Label.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        font4Label.setForeground(new java.awt.Color(230, 224, 236));
        font4Label.setText("Greetings");
        font4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font4Clicked(evt);
            }
        });

        font5Label.setBackground(new java.awt.Color(51, 153, 255));
        font5Label.setFont(new java.awt.Font("Mistral", 0, 36)); // NOI18N
        font5Label.setForeground(new java.awt.Color(230, 224, 236));
        font5Label.setText("Greetings");
        font5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font5Clicked(evt);
            }
        });

        finalizeButton.setBackground(new java.awt.Color(50, 255, 255));
        finalizeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        finalizeButton.setText("Set");
        finalizeButton.setMargin(new java.awt.Insets(0, 5, 0, 5));
        finalizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeButtonActionPerformed(evt);
            }
        });

        finishButton.setBackground(new java.awt.Color(50, 255, 255));
        finishButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        finishButton.setText("Finish");
        finishButton.setMargin(new java.awt.Insets(0, 5, 0, 5));
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        instructionTextArea.setEditable(false);
        instructionTextArea.setBackground(new java.awt.Color(50, 150, 255));
        instructionTextArea.setColumns(20);
        instructionTextArea.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        instructionTextArea.setRows(5);
        instructionTextArea.setBorder(null);
        instructionScrollPane.setViewportView(instructionTextArea);

        colorBlackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FontColorBlack.jpg"))); // NOI18N
        colorBlackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackClicked(evt);
            }
        });

        colorWhiteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FontColorWhite.jpg"))); // NOI18N
        colorWhiteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteClicked(evt);
            }
        });

        color3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor3.jpg"))); // NOI18N
        color3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color3Clicked(evt);
            }
        });

        color4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor4.jpg"))); // NOI18N
        color4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color4Clicked(evt);
            }
        });

        color5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor5.jpg"))); // NOI18N
        color5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color5Clicked(evt);
            }
        });

        color6Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor6.jpg"))); // NOI18N
        color6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color6Clicked(evt);
            }
        });

        color7Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor7.jpg"))); // NOI18N
        color7Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color7Clicked(evt);
            }
        });

        color8Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor8.jpg"))); // NOI18N
        color8Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color8Clicked(evt);
            }
        });

        color9Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor9.jpg"))); // NOI18N
        color9Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color9Clicked(evt);
            }
        });

        color10Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor10.jpg"))); // NOI18N
        color10Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color10Clicked(evt);
            }
        });

        color11Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor11.jpg"))); // NOI18N
        color11Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color11Clicked(evt);
            }
        });

        color12Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor12.jpg"))); // NOI18N
        color12Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color12Clicked(evt);
            }
        });

        color13Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor13.jpg"))); // NOI18N
        color13Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color13Clicked(evt);
            }
        });

        color14Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor14.jpg"))); // NOI18N
        color14Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color14Clicked(evt);
            }
        });

        color15Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontcolor15.jpg"))); // NOI18N
        color15Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color15Clicked(evt);
            }
        });

        font6Label.setBackground(new java.awt.Color(51, 153, 255));
        font6Label.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 24)); // NOI18N
        font6Label.setForeground(new java.awt.Color(230, 224, 236));
        font6Label.setText("Greetings");
        font6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font6Clicked(evt);
            }
        });

        font2Label.setBackground(new java.awt.Color(51, 153, 255));
        font2Label.setFont(new java.awt.Font("Curlz MT", 0, 24)); // NOI18N
        font2Label.setForeground(new java.awt.Color(230, 224, 236));
        font2Label.setText("Greetings");
        font2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font2Clicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout finalizePanelLayout = new org.jdesktop.layout.GroupLayout(finalizePanel);
        finalizePanel.setLayout(finalizePanelLayout);
        finalizePanelLayout.setHorizontalGroup(
            finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(finalizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(finalizePanelLayout.createSequentialGroup()
                        .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(smallerFontButton)
                                .add(103, 103, 103)
                                .add(largerFontButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(colorBlackLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(colorWhiteLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color3Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(color5Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color4Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color6Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(color7Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color8Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color9Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(color10Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color11Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color12Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, fontColorLabel)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, fontTypeLabel)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, instructionScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 431, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(color13Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color14Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(color15Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, finalizePanelLayout.createSequentialGroup()
                                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(font3Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(font5Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(59, 59, 59)
                                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(font6Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(font2Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, finalizePanelLayout.createSequentialGroup()
                        .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(finalizePanelLayout.createSequentialGroup()
                                .add(finalizeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(finishButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(finalizePanelLayout.createSequentialGroup()
                                .add(font1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(font4Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(48, 48, 48))))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 222, Short.MAX_VALUE)
                    .add(fontBlackLabel)
                    .add(0, 221, Short.MAX_VALUE)))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 222, Short.MAX_VALUE)
                    .add(fontRedLabel)
                    .add(0, 221, Short.MAX_VALUE)))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 222, Short.MAX_VALUE)
                    .add(fontGreenLabel)
                    .add(0, 221, Short.MAX_VALUE)))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 222, Short.MAX_VALUE)
                    .add(fontPurpleLabel)
                    .add(0, 221, Short.MAX_VALUE)))
        );
        finalizePanelLayout.setVerticalGroup(
            finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(finalizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(instructionScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smallerFontButton)
                    .add(largerFontButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(fontColorLabel)
                .add(18, 18, 18)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, colorBlackLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, colorWhiteLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, color3Label))
                .add(18, 18, 18)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(color4Label)
                    .add(color5Label)
                    .add(color6Label))
                .add(18, 18, 18)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(finalizePanelLayout.createSequentialGroup()
                        .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(color8Label)
                            .add(color7Label))
                        .add(18, 18, 18)
                        .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(finalizePanelLayout.createSequentialGroup()
                                .add(color12Label)
                                .add(18, 18, 18)
                                .add(color15Label)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(finalizePanelLayout.createSequentialGroup()
                                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(color10Label)
                                    .add(color11Label))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(color14Label)
                                    .add(color13Label)))))
                    .add(color9Label))
                .add(36, 36, 36)
                .add(fontTypeLabel)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(font1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(font4Label))
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(font3Label)
                    .add(font2Label))
                .add(18, 18, 18)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(font5Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(font6Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(finalizeButton)
                    .add(finishButton))
                .add(238, 238, 238))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 519, Short.MAX_VALUE)
                    .add(fontBlackLabel)
                    .add(0, 518, Short.MAX_VALUE)))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 519, Short.MAX_VALUE)
                    .add(fontRedLabel)
                    .add(0, 518, Short.MAX_VALUE)))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 519, Short.MAX_VALUE)
                    .add(fontGreenLabel)
                    .add(0, 518, Short.MAX_VALUE)))
            .add(finalizePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(finalizePanelLayout.createSequentialGroup()
                    .add(0, 519, Short.MAX_VALUE)
                    .add(fontPurpleLabel)
                    .add(0, 518, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(finalizePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(finalizePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 807, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void smallerFontButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
//        fontsize = 72;
//        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                                                 

    private void largerFontButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
//        fontsize = 150;
//        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                                                

    private void redClicked(java.awt.event.MouseEvent evt) {                            
        IJ.setForegroundColor(255, 0, 0); //red
    }                           

    private void blackClicked(java.awt.event.MouseEvent evt) {                              
        IJ.setForegroundColor(0, 0, 0); //black
    }                             

    private void greenClicked(java.awt.event.MouseEvent evt) {                              
        IJ.setForegroundColor(0, 255, 0); //green
    }                             

    private void purpleClicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(209, 93, 254); //purple
    }                              

    private void font1Clicked(java.awt.event.MouseEvent evt) {                              
        fonttype = "Ariel";
        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                             

    private void font2Clicked(java.awt.event.MouseEvent evt) {                              
        fonttype = "Curlz MT";
        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                             

    private void font3Clicked(java.awt.event.MouseEvent evt) {                              
        fonttype = "Edwardian Script ITC";
        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                             

    private void font4Clicked(java.awt.event.MouseEvent evt) {                              
        fonttype = "Lucida Handwriting";
        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                             

    private void font5Clicked(java.awt.event.MouseEvent evt) {                              
        fonttype = "Mistral";
        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                             

    private void font6Clicked(java.awt.event.MouseEvent evt) {                              
        fonttype = "Plantagenet Cherokee";
        TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
    }                             

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             

        ImagePlus imp = IJ.getImage();
        
        boolean isRoi = imp.getRoi() != null;
        if (isRoi) {
            IJ.run(imp, "Draw", "");
            IJ.run(imp, "Select None", "");
        }

        AAPC_Var.hideFinalize();

        PrintCard pc = new PrintCard();
        pc.setVisible(true);

    }                                            

    private void finalizeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               

        ImagePlus imp = IJ.getImage();
        
        boolean isRoi = imp.getRoi() != null;
        if (isRoi) {
            IJ.run(imp, "Draw", "");
            IJ.run(imp, "Select None", "");
        }

    }                                              

    private void whiteClicked(java.awt.event.MouseEvent evt) {                              
        IJ.setForegroundColor(255, 255, 255); //white
    }                             

    private void smallerFontMousePressed(java.awt.event.MouseEvent evt) {                                         

        fontsize--;

        repeatTimer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                fontsize--;
                TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
            }
        });
        repeatTimer.setInitialDelay(10); // start repeating only after 1 second
        repeatTimer.start();

    }                                        

    private void largerFontMousePressed(java.awt.event.MouseEvent evt) {                                        

        fontsize++;

        repeatTimer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                fontsize++;
                TextRoi.setFont(fonttype, fontsize, Font.PLAIN);
            }
        });
        repeatTimer.setInitialDelay(10); // start repeating only after 1 second
        repeatTimer.start();

    }                                       

    private void smallFontMouseReleased(java.awt.event.MouseEvent evt) {                                        

        repeatTimer.stop();

    }                                       

    private void largeFontMouseReleased(java.awt.event.MouseEvent evt) {                                        

        repeatTimer.stop();

    }                                       

    private void color3Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(147, 98, 49); //black
    }                              

    private void color4Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(192, 0, 0); //black
    }                              

    private void color5Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(255, 0, 0); //black
    }                              

    private void color6Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(255, 192, 0); //black
    }                              

    private void color7Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(255, 153, 204); //black
    }                              

    private void color8Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(255, 255, 0); //black
    }                              

    private void color9Clicked(java.awt.event.MouseEvent evt) {                               
        IJ.setForegroundColor(153, 255, 51); //black
    }                              

    private void color10Clicked(java.awt.event.MouseEvent evt) {                                
        IJ.setForegroundColor(146, 208, 80); //black
    }                               

    private void color11Clicked(java.awt.event.MouseEvent evt) {                                
        IJ.setForegroundColor(0, 176, 80); //black
    }                               

    private void color12Clicked(java.awt.event.MouseEvent evt) {                                
        IJ.setForegroundColor(125, 221, 255); //black
    }                               

    private void color13Clicked(java.awt.event.MouseEvent evt) {                                
        IJ.setForegroundColor(0, 112, 192); //black
    }                               

    private void color14Clicked(java.awt.event.MouseEvent evt) {                                
        IJ.setForegroundColor(0, 32, 96); //black
    }                               

    private void color15Clicked(java.awt.event.MouseEvent evt) {                                
        IJ.setForegroundColor(112, 68, 160); //black
    }                               

    public void toTextWindow(String s, Boolean go) {
        if (go) {
            String s1 = instructionTextArea.getText();
            String s2 = "\n*******************\n";
            instructionTextArea.setText(s1 + s2 + s);
        } else {
            instructionTextArea.setText(s);
        }
    }

    private void moveWindow(ImagePlus impl, int x, int y) {

        impl.getWindow().setLocation(x, y);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizePC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizePC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizePC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizePC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizePC().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel color10Label;
    private javax.swing.JLabel color11Label;
    private javax.swing.JLabel color12Label;
    private javax.swing.JLabel color13Label;
    private javax.swing.JLabel color14Label;
    private javax.swing.JLabel color15Label;
    private javax.swing.JLabel color3Label;
    private javax.swing.JLabel color4Label;
    private javax.swing.JLabel color5Label;
    private javax.swing.JLabel color6Label;
    private javax.swing.JLabel color7Label;
    private javax.swing.JLabel color8Label;
    private javax.swing.JLabel color9Label;
    private javax.swing.JLabel colorBlackLabel;
    private javax.swing.JLabel colorWhiteLabel;
    private javax.swing.JButton finalizeButton;
    private javax.swing.JPanel finalizePanel;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel font1Label;
    private javax.swing.JLabel font2Label;
    private javax.swing.JLabel font3Label;
    private javax.swing.JLabel font4Label;
    private javax.swing.JLabel font5Label;
    private javax.swing.JLabel font6Label;
    private javax.swing.JLabel fontBlackLabel;
    private javax.swing.JLabel fontColorLabel;
    private javax.swing.JLabel fontGreenLabel;
    private javax.swing.JLabel fontPurpleLabel;
    private javax.swing.JLabel fontRedLabel;
    private javax.swing.JLabel fontTypeLabel;
    private javax.swing.JScrollPane instructionScrollPane;
    private javax.swing.JTextArea instructionTextArea;
    private javax.swing.JButton largerFontButton;
    private javax.swing.JButton smallerFontButton;
    // End of variables declaration                   
    // global variables
    Timer repeatTimer;
    ImagePlus imp;
    String fonttype = "Comic Sans MS";
    int fontsize = 72;
}
