import ij.IJ;
import ij.ImagePlus;
import ij.gui.Roi;
import java.awt.Rectangle;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author chris
 */
public class OutlineSubject extends javax.swing.JFrame {

    /**
     * Creates new form OutlineSubject
     */
    public OutlineSubject() {
        initComponents();

        language = AAPC_Var.getLanguage();

        setLanguage();

        img = IJ.getImage();

        IJ.setTool("freehand");
        IJ.run(img, "Select None", "");
        IJ.run("Colors...", "foreground=white background=black selection=red");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        outlineSubjectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionTextArea = new javax.swing.JTextArea();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(31, 73, 125));

        outlineSubjectPanel.setBackground(new java.awt.Color(51, 51, 255));

        instructionTextArea.setBackground(new java.awt.Color(50, 150, 255));
        instructionTextArea.setColumns(20);
        instructionTextArea.setRows(5);
        jScrollPane1.setViewportView(instructionTextArea);

        continueButton.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        continueButton.setText("Continue...");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout outlineSubjectPanelLayout = new org.jdesktop.layout.GroupLayout(outlineSubjectPanel);
        outlineSubjectPanel.setLayout(outlineSubjectPanelLayout);
        outlineSubjectPanelLayout.setHorizontalGroup(
            outlineSubjectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(outlineSubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(continueButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        outlineSubjectPanelLayout.setVerticalGroup(
            outlineSubjectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(outlineSubjectPanelLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(continueButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(outlineSubjectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(outlineSubjectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               

        if (img.getRoi() != null) {

            Roi roi = img.getRoi();

            Rectangle rec = roi.getBounds();

            int x = rec.x;
            int y = rec.y;
            int w = rec.width;
            int h = rec.height;

            img.setRoi(x, y, w, h);

            IJ.run(img, "Crop", "");

            AAPC_Var.hideOutlineSubject();

            WandFrame wf = new WandFrame();
            wf.setVisible(true);

            AAPC_Var.setWandFrame(wf);

        } else {
            IJ.error("You must first outline the subject before isolation");
        }

    }                                              

    private void setLanguage() {

        String s;

        switch (language) {

            case 0:

                s = "Outline the subject, then click continue.";

                toInstructionWidow(s, false);
                continueButton.setText("Continue...");
                break;

            case 1:

                s = "Skizzieren Sie das Thema und klicken Sie auf weiter.";
                toInstructionWidow(s, false);
                continueButton.setText("Weiter...");
                break;

            case 2:

                s = "Décrivez l'objet, puis cliquez sur continuer.";
                toInstructionWidow(s, false);
                continueButton.setText("Continuer...");
                break;

            case 3:

                s = "Delineare il soggetto, quindi su Continua.";
                toInstructionWidow(s, false);
                continueButton.setText("Continuare...");
                break;

            case 4:

                s = "Kiswahili Inastrucions";
                toInstructionWidow(s, false);
                continueButton.setText("ugh...");
                break;

        }

    }

    private void toInstructionWidow(String s, Boolean go) {
        if (go) {
            String s1 = instructionTextArea.getText();
            String s2 = "\n*******************\n";
            instructionTextArea.setText(s1 + s2 + s);
        } else {
            instructionTextArea.setText(s);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutlineSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutlineSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutlineSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutlineSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutlineSubject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton continueButton;
    private javax.swing.JTextArea instructionTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel outlineSubjectPanel;
    // End of variables declaration                   
    // global variables
    ImagePlus img;
    int language;
}
