import ij.IJ;
import ij.ImagePlus;
import ij.gui.ImageWindow;
import ij.gui.Roi;
import ij.io.OpenDialog;
import ij.plugin.Duplicator;
import java.awt.Rectangle;

/*
 * PickSubject.java
 *
 * Created on Jul 4, 2012, 9:26:25 AM
 */
/**
 * Copyright Jun 7, 2012 The GAIA Group
 * http://gaiag.net
 *
 * @author chris
 */
public class PickSubject extends javax.swing.JFrame {

    /** Creates new form PickSubject */
    public PickSubject() {
        initComponents();
        
        imp = IJ.getImage();
//        IJ.setTool("rectangle");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        connectLabel = new javax.swing.JLabel();
        connect2Label = new javax.swing.JLabel();
        connect2Label1 = new javax.swing.JLabel();
        subjectButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        connectLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        connectLabel.setForeground(new java.awt.Color(255, 255, 255));
        connectLabel.setText("Please connect a data device ");

        connect2Label.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        connect2Label.setForeground(new java.awt.Color(255, 255, 255));
        connect2Label.setText("(e.g., USB-stick, SB card)");

        connect2Label1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        connect2Label1.setForeground(new java.awt.Color(255, 255, 255));
        connect2Label1.setText("Then click the subject button.");

        subjectButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        subjectButton.setText("Subject");
        subjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(connectLabel)
                        .add(5, 5, 5)
                        .add(connect2Label))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(connect2Label1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(subjectButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(backButton)
                .add(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(connectLabel)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(connect2Label)))
                .add(9, 9, 9)
                .add(connect2Label1)
                .add(22, 22, 22)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(subjectButton)
                    .add(backButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void subjectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

        AAPC_Var.hidePicSubject();

        OpenDialog opendialog = new OpenDialog("Select image containing the subject.", "");

        if (opendialog.getFileName() == null) {
            return;
        }

        String s2 = opendialog.getDirectory();
        String s3 = opendialog.getFileName();

        ImagePlus img = IJ.openImage(s2 + s3);

        int k = s3.lastIndexOf('.');

        IJ.run(img, "Set Scale...", "distance=0 known=0 pixel=1 unit=pixel");

        img = setupSubject(img);
        
        img.show();

        ImageWindow iw = new ImageWindow(img);

        iw.maximize();
        
        moveWindow(img, 600, 0);

        OutlineSubject os = new OutlineSubject();
        os.setVisible(true);
        
        AAPC_Var.setOutlineSubject(os);
        
    }                                             

    private ImagePlus setupSubject(ImagePlus ip) {

        ImagePlus ims = new Duplicator().run(ip);

        ims.setTitle("Subject");

//        imp = AAPC_Var.getImage();
        
        moveWindow(imp, 400, 0);
        
        imp.setRoi(1126, 181, 343, 975);
        
        AAPC_Var.setROI(imp.getRoi());

        Roi PCroi = imp.getRoi();

        Rectangle PCrec = PCroi.getBounds();

        int pcX = PCrec.x;
        AAPC_Var.setPCX(pcX);
        
        int pcY = PCrec.y;
        AAPC_Var.setPCY(pcY);
        
        double pcW = PCrec.getWidth();
        AAPC_Var.setPCW(pcW);
        
        double pcH = PCrec.getHeight();
        AAPC_Var.setPCH(pcH);

        int subw = ims.getWidth();
        int subh = ims.getHeight();

        double ht = PCrec.getHeight();
        double wt = (double) (subw / subh) * ht;

        IJ.run(ims, "Size...", "width="
                + wt + " height="
                + ht + " constrain average interpolation=Bilinear");
        
        IJ.run(imp, "Select None", "");
        
        return ims;

    }
       
    private void moveWindow(ImagePlus impl, int x, int y) {

        impl.getWindow().setLocation(x, y);

    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           

        AAPC_Var.hidePicSubject();
        AAPC_Var.showYourImage();
        imp.hide();

    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PickSubject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JLabel connect2Label;
    private javax.swing.JLabel connect2Label1;
    private javax.swing.JLabel connectLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton subjectButton;
    // End of variables declaration                   

    // Global variables
    
    ImagePlus imp;
}

