import ij.IJ;
import ij.ImagePlus;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/*
 * NewIdeas.java
 *
 * Created on Jun 16, 2012, 10:09:13 AM
 */
/**
 * Copyright Jun 7, 2012 The GAIA Group
 * http://gaiag.net
 *
 * @author chris
 */
public class PostCard extends javax.swing.JFrame {

    /** Creates new form NewIdeas */
    public PostCard() {

        screen = Toolkit.getDefaultToolkit().getScreenSize();
        screenHeight = screen.height;
        screenWidth = screen.width;
        
        initComponents();
        
        IJ.run("Misc...", "divide=Infinity require");

        setLabels();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        postcardPanel = new javax.swing.JPanel();
        EnglandLabel = new javax.swing.JLabel();
        GermanLabel = new javax.swing.JLabel();
        FranceLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        ItalyLabel = new javax.swing.JLabel();
        createOwnCardButton = new javax.swing.JButton();
        pic1Label = new javax.swing.JLabel();
        putOwnImageButton = new javax.swing.JButton();
        pic2Label = new javax.swing.JLabel();
        figureJButton = new javax.swing.JButton();
        spainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        setSize(screenWidth, screenHeight
        );

        postcardPanel.setBackground(new java.awt.Color(51, 51, 255));

        EnglandLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/English.jpg"))); // NOI18N
        EnglandLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnglishLanguageClicked(evt);
            }
        });

        GermanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/German.jpg"))); // NOI18N
        GermanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GermanLanguageClicked(evt);
            }
        });

        FranceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/France.jpg"))); // NOI18N
        FranceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frenchLanguageClicked(evt);
            }
        });

        TitleLabel.setBackground(new java.awt.Color(31, 73, 125));
        TitleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(230, 224, 236));
        TitleLabel.setText("Create your own post card in just a few minutes!");

        ItalyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Italy.jpg"))); // NOI18N
        ItalyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianLanguageClicked(evt);
            }
        });

        createOwnCardButton.setBackground(new java.awt.Color(79, 129, 189));
        createOwnCardButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        createOwnCardButton.setForeground(new java.awt.Color(230, 224, 236));
        createOwnCardButton.setText("Create a postcard from up to 4 of your own pictures");
        createOwnCardButton.setBorderPainted(false);
        createOwnCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOwnCardButtonActionPerformed(evt);
            }
        });

        pic1Label.setBackground(new java.awt.Color(31, 73, 125));
        pic1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic1canada.jpg"))); // NOI18N
        pic1Label.setMaximumSize(new java.awt.Dimension(650, 540));
        pic1Label.setMinimumSize(new java.awt.Dimension(650, 540));
        pic1Label.setPreferredSize(new java.awt.Dimension(650, 540));
        pic1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pic1MouseClicked(evt);
            }
        });

        putOwnImageButton.setBackground(new java.awt.Color(79, 129, 189));
        putOwnImageButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        putOwnImageButton.setForeground(new java.awt.Color(230, 224, 236));
        putOwnImageButton.setText("Put your own image into one of our postcard templates");
        putOwnImageButton.setBorderPainted(false);
        putOwnImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putOwnImageButtonActionPerformed(evt);
            }
        });

        pic2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2koln.jpg"))); // NOI18N
        pic2Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pic2Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pic2Label.setMaximumSize(new java.awt.Dimension(650, 540));
        pic2Label.setMinimumSize(new java.awt.Dimension(650, 540));
        pic2Label.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pic2Label.setVerifyInputWhenFocusTarget(false);
        pic2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pic2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pic2MouseClicked(evt);
            }
        });

        figureJButton.setBackground(new java.awt.Color(79, 129, 189));
        figureJButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        figureJButton.setText("Use FigureJ");
        figureJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                figureJButtonActionPerformed(evt);
            }
        });

        spainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spanish.jpg"))); // NOI18N
        spainLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spanishLanguageClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout postcardPanelLayout = new org.jdesktop.layout.GroupLayout(postcardPanel);
        postcardPanel.setLayout(postcardPanelLayout);
        postcardPanelLayout.setHorizontalGroup(
            postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(postcardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(postcardPanelLayout.createSequentialGroup()
                        .add(TitleLabel)
                        .add(29, 29, 29)
                        .add(EnglandLabel)
                        .add(18, 18, 18)
                        .add(GermanLabel)
                        .add(18, 18, 18)
                        .add(FranceLabel)
                        .add(18, 18, 18)
                        .add(ItalyLabel)
                        .add(18, 18, 18)
                        .add(spainLabel))
                    .add(postcardPanelLayout.createSequentialGroup()
                        .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pic1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(createOwnCardButton))
                        .add(29, 29, 29)
                        .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(putOwnImageButton)
                            .add(pic2Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 799, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .add(postcardPanelLayout.createSequentialGroup()
                .add(95, 95, 95)
                .add(figureJButton)
                .add(0, 0, Short.MAX_VALUE))
        );
        postcardPanelLayout.setVerticalGroup(
            postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(postcardPanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(EnglandLabel)
                        .add(TitleLabel)
                        .add(GermanLabel)
                        .add(FranceLabel)
                        .add(ItalyLabel))
                    .add(postcardPanelLayout.createSequentialGroup()
                        .add(spainLabel)
                        .add(6, 6, 6)))
                .add(21, 21, 21)
                .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pic1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 465, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pic2Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 539, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(postcardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(createOwnCardButton)
                    .add(putOwnImageButton))
                .add(18, 18, 18)
                .add(figureJButton)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(postcardPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(postcardPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void EnglishLanguageClicked(java.awt.event.MouseEvent evt) {                                        
        
        language = 0;
        
        AAPC_Var.setLanguage(language);
        
        String eng = "Create your own post card in just a few minutes!";
        TitleLabel.setText(eng);
        
        eng = "Create a postcard from up to 4 of your own pictures";
        createOwnCardButton.setText(eng);
        
        eng = "Put your own image into one of our postcard templates";
        putOwnImageButton.setText(eng);
        
    }                                       

    private void GermanLanguageClicked(java.awt.event.MouseEvent evt) {                                       
        
        language = 1;
        
        AAPC_Var.setLanguage(language);
        
        String ger = "Erstellen Sie Ihre Postkarte in nur wenigen Minuten";
        TitleLabel.setText(ger);
        
        ger = "Postkarte aus bis zu 4 eigenen Fotos erstellen";
        createOwnCardButton.setText(ger);
        
        ger = "Kreative Karte erstellen aus Vorlage und eigenem Bild";
        putOwnImageButton.setText(ger);
    }                                      

    private void createOwnCardButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    

        ourCard();
        
    }                                                   

    private void putOwnImageButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  

        yourCard();
        
    }                                                 

    private void frenchLanguageClicked(java.awt.event.MouseEvent evt) {                                       
        
        language = 2;
        
        AAPC_Var.setLanguage(language);
        
        String spa = "French not yet implemented";
        TitleLabel.setText(spa);
        
        spa = "French not yet implemented";
        createOwnCardButton.setText(spa);
        
        spa = "French not yet implemented";
        putOwnImageButton.setText(spa);
        
    }                                      

    private void ItalianLanguageClicked(java.awt.event.MouseEvent evt) {                                        
        
        language = 3;
        
        AAPC_Var.setLanguage(language);
        
        String ita = "Italian not yet implemented";
        TitleLabel.setText(ita);
        
        ita = "Italian not yet implemented";
        createOwnCardButton.setText(ita);
        
        ita = "Italian not yet implemented";
        putOwnImageButton.setText(ita);

    }                                       

    private void pic1MouseClicked(java.awt.event.MouseEvent evt) {                                  

        ourCard();
        
    }                                 

    private void pic2MouseClicked(java.awt.event.MouseEvent evt) {                                  

        yourCard();
        
    }                                 

    private void figureJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

        AAPC_Var.hidePostCard();

        Text_Tool tt = new Text_Tool();
        tt.setVisible(true);
        
        IJ.run("FigureJ ", "");
        
    }                                             

    private void spanishLanguageClicked(java.awt.event.MouseEvent evt) {                                        
        
        language = 4;
        
        AAPC_Var.setLanguage(language);
        
        String spa = "Spanish not yet implemented";
        TitleLabel.setText(spa);
        
        spa = "Spanish not yet implemented";
        createOwnCardButton.setText(spa);
        
        spa = "Spanish not yet implemented";
        putOwnImageButton.setText(spa);
        
    }                                       

    
    private BufferedImage image;

    public void ImagePanel() {

        ImagePlus eng = new ImagePlus();   //English.jpg;

        try {
            image = ImageIO.read(new File("image name and path"));
        } catch (IOException ex) {
            // handle exception...
        }
    }

    public void paintComponent(Graphics g) {
        g.drawImage(image, 0, 0, null); // see javadoc for more info on the parameters

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PostCard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel EnglandLabel;
    private javax.swing.JLabel FranceLabel;
    private javax.swing.JLabel GermanLabel;
    private javax.swing.JLabel ItalyLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton createOwnCardButton;
    private javax.swing.JButton figureJButton;
    private javax.swing.JLabel pic1Label;
    private javax.swing.JLabel pic2Label;
    private javax.swing.JPanel postcardPanel;
    private javax.swing.JButton putOwnImageButton;
    private javax.swing.JLabel spainLabel;
    // End of variables declaration                   

    // Global Variables
    
    Dimension screen;
    PostCard postc;
    int screenHeight;
    int screenWidth;
    int language = 0; // 0 = English, 1 = Deutsch, 2 = Spanish, 3 = Italian

    void transfer(PostCard pc) {
        
        postc = pc;
        
    }

    private void setLabels() {
        
        pic1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic1canada.jpg")));
        pic2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic2koln.jpg")));
        
    }

    private void ourCard() {
        
        ChooseCardTemplate cc = new ChooseCardTemplate();
        AAPC_Var.putChooseCardTemplate(cc);
        
        AAPC_Var.showChooseCard();
        AAPC_Var.hidePostCard();
        
    }

    private void yourCard() {
        
        YourImage yi = new YourImage();
        AAPC_Var.putYourImage(yi);

        AAPC_Var.showYourImage();
        AAPC_Var.hidePostCard();
        
    }

}